{% set name = "bulk" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bulk-{{ version }}.tar.gz
  sha256: 723df8f5da7c25db62a5bf25f10ca071cc8451ccfcf8f402c155834187835d38

build:
  entry_points:
    - bulk = bulk.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bokeh >=2.4.3,<3.0.0
    - pandas >=1.0.0,<2.0.0
    - python >=3.6
    - typer >=0.4.1,<1.0.0

test:
  imports:
    - bulk
  commands:
    - pip check
    - bulk --help
  requires:
    - pip

about:
  home: https://github.com/koaning/bulk
  license: MIT
  license_file: LICENSE
  summary: A Simple Bulk Labelling Tool

extra:
  recipe-maintainers:
    - thewchan
