{% set name = "bulk" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bulk-{{ version }}.tar.gz
  sha256: 47ca1ddbc84aefc5a4e17ddddc83a76371aba16bf02799220e450fdb7ef2bae9

build:
  entry_points:
    - bulk = bulk.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - radicli >=0.0.8,<0.1.0
    - bokeh >=2.4.3,<3.0.0
    # Upstream has only pandas>=1.0.0, but there seems to be backward incompatibility with numpy bool8 datatype
    - pandas >=1.0.0,<2.0.0
    - wasabi >=0.9.1

test:
  imports:
    - bulk
  commands:
    - pip check
    # Upstream cli broken disabling right now
    # - bulk --help
  requires:
    - pip

about:
  home: https://github.com/koaning/bulk
  license: MIT
  license_file: LICENSE
  summary: A Simple Bulk Labelling Tool

extra:
  recipe-maintainers:
    - thewchan
