{% set name = "bulk" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bulk-{{ version }}.tar.gz
  sha256: aca78427e0844738352b5c9caf53d7ae37b93fd60d087adac0e92551dbf9e3bd

build:
  entry_points:
    - bulk = bulk.__main__:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - radicli >=0.0.8,<0.1.0
    - bokeh >=2.4.3,<3.0.0
    # Upstream has only pandas>=1.0.0, but there seems to be backward incompatibility with numpy bool8 datatype
    - pandas >=1.0.0,<2.0.0
    - wasabi >=0.9.1
    - numpy <2
    - jupyter-scatter
    - scikit-learn

test:
  imports:
    - bulk
  commands:
    - pip check
    # Upstream cli broken disabling right now
    # - bulk --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/koaning/bulk
  license: MIT
  license_file: LICENSE
  summary: A Simple Bulk Labelling Tool

extra:
  recipe-maintainers:
    - thewchan
